RestApp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('',views.IndexMain.as_view()),
]

RestApp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), # /blog/
    # # 글 상세 조회
    # path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'), # /blog/detail/1
    # # 글 작성
    path("write/", views.Write.as_view(), name='write'), # /blog/write/
    # # 글 수정
    # path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # # 글 삭제
    # path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # # 코멘트 작성
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # # 코멘트 삭제
    # path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    # # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # # 태그 삭제
    # path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

RestApp/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # user/register
    # 회원가입
    path("register/", views.Registration.as_view(), name='register'),
    # # 로그인
    path("login/", views.Login.as_view(), name="login"),
    # # 로그아웃
    path("logout/", views.Logout.as_view(), name='logout'),
    path("profile/write/", views.ProfileWrite.as_view(), name='pf-write'),
    path("profile/update/", views.ProfileUpdate.as_view(), name='pf-update'),
    path("profile/delete/", views.ProfileDelete.as_view(), name='pf-delete'),
]

RestApp/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <title>
            {% block title %}
                {{ title }}
            {% endblock %}
        </title>
    </head>
    <body>

        <div class="container">
            {% if user.is_authenticated %}
            <p>Welcome, {{ user.email }}</p>
            <a href="{% url 'user:logout' %}">Logout</a>
            {% else %}
            <p>Please, Login</p>
            <a href="{% url 'user:login' %}">Login</a>
            {% endif %}
            <h1>Blog</h1>
            {% block content %}
            {% endblock %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    </body>
</html>
   

RestApp/templates/index.html
{% extends 'base.html' %} 
{% load i18n %} 
{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'user:logout' %}">로그아웃</a>
        <a href="{% url 'blog:list' %}">블로그</a>
    {% else %}
        <a href="{% url 'user:login' %}">로그인</a>
        <a href="{% url 'user:register' %}">회원가입</a>
    {% endif %} 
{% endblock %}