RestApp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('',views.IndexMain.as_view()),
]

RestApp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), # /blog/
    # # 글 상세 조회
    # path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'), # /blog/detail/1
    # # 글 작성
    path("write/", views.Write.as_view(), name='write'), # /blog/write/
    # # 글 수정
    # path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # # 글 삭제
    # path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # # 코멘트 작성
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # # 코멘트 삭제
    # path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    # # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # # 태그 삭제
    # path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

RestApp/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    # on_delete는 참조하는 post가 지워질 경우 같이 삭제한다는 옵션
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE) 
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Comment on {self.post.title}'


class HashTag(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE) 
    name = models.CharField(max_length=10)
    
    def __str__(self):
        return self.name

RestApp/blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

# Form: html에 있는 form 태그
# Model Form: model을 사용하는 form
# 유효성 검사를 위해서 이렇게 사용함
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content']
        

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'cols': '50','rows': '2'})
        }


class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = ['name']

RestApp/blog/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Post, Comment, HashTag
from .forms import PostForm
from .serializers import PostSerializer, CommentSerializer, HashtagSerializer


### post
class Index(APIView):
    def get(self, request):
        posts = Post.objects.all()
        serialized_posts = PostSerializer(posts, many=True) # 직렬화
        return Response(serialized_posts.data)


class Write(APIView):
    def post(self, request):
        serializer = PostSerializer(data=request.POST)
        if serializer.is_valid():
            post = serializer.save(writer=request.user)
            post.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

class Update(APIView):
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        serializer = PostSerializer(post)
        return Response(serializer.data)

    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        serializer = PostSerializer(post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Delete(APIView):
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        post.delete()
        return Response({'message': 'Post deleted'}, status=status.HTTP_200_OK)
    
### Comment
class CommentWrite(APIView):
    def post(self, request, pk):
        serializer = CommentSerializer(data=request.POST)
        
        if serializer.is_valid():
            
            comment = serializer.save(writer=request.user)
            comment.save()
            
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST) 


class CommentDelete(APIView):
    def post(self, request, pk):
        comment = Comment.objects.get(pk=pk)
        comment.delete()
        serializer = CommentSerializer(comment)
        return Response(serializer.data, status=status.HTTP_204_NO_CONTENT)
    
    
### hashtag
class HashTagWrite(APIView):
    def post(self, request, pk):
        
        serializer = HashtagSerializer(data=request.POST)
        
        if serializer.is_valid():
            
            hashtag = serializer.save(writer=request.user)
            hashtag.save()
            
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class HashTagDelete(APIView):
    def post(self, request, pk):
        hashtag = HashTag.objects.get(pk=pk)
        hashtag.delete()
        serializer = HashtagSerializer(hashtag)
        return Response(serializer.data, status=status.HTTP_204_NO_CONTENT)

RestApp/blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
    {{ form }}
</div>

RestApp/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <h2>제목: {{ post.title }}</h2>

    {% if post.writer == request.user %}
    <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn">
    </form>
    {% endif %}

    <p>내용: {{ post.content }}</p>
    <p>작성자: {{ post.writer.email }}</p>
    <p>작성일: {{ post.created_at }}</p>
    <hr>

    <!-- 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            {% with form=comment_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ comment_form.content }}
        {% endif %}
        <input type="submit" value="댓글 작성">
    </form>
    <br>
    <!-- comments -->
    <!-- if 문 -->
    {% if comments %}
        <!-- for 문 -->
        <ul>
            {% for comment in comments %}
            <!-- 내용, 작성시간, 삭제 버튼 -->
                <li>{{ comment.content }} / {{ comment.created_at }}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class='btn'>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>댓글이 없습니다.</p>
    {% endif %}
    <hr>
    <!-- 태그작성 화면 -->
    <h3>해시태그</h3>
    <form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {% if hashtag_form.errors %}
            {% with form=hashtag_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ hashtag_form.name }}
        {% endif %}
        <input type="submit" value="태그 작성">
    </form>
    {% if hashtags %}
    <ul>
        {% for hashtag in hashtags %}
        <li>
            {{ hashtag }}
            {% if hashtag.writer == request.user %}
                <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="X" class='btn'>
                </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <br>
    <p>해시태그가 없습니다.</p>
    {% endif %}


{% endblock %}

RestApp/blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
    {% include 'blog/form_error.html' %}
{% else %}
    <form action="{% url 'blog:edit' pk=post.pk%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value = "수정">
    </form>
{% endif %}
{% endblock %}

RestApp/blog/templates/blog/post_form.html
{% extends 'base.html' %} 

{% block content %}
    <h2>블로그 글 작성 화면</h2>
    <!-- 제목 -->
    <!-- 내용 -->
    <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-success">
    </form>
{% endblock %}

RestApp/blog/templates/blog/post_list.html
{% extends 'base.html' %} 

{% block content %}
    <p>블로그 게시판 첫 화면 입니다.</p>
    <!-- url 'app_name:name' -->
    <form action="{% url 'blog:write' %}" method="get">
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.GET.next }}">
        <input type="submit" value="글 작성">
    </form>
    <!-- 조건문 -->
    <!-- 글이 있을 때 : 테이블 출력 -->
    {% if posts %}
    <table class="table table-bordered">
        <thead class="table-light">
            <tr>
                <th>제목</th>
                <th>작성자</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr>
                    <td><a class="btn" href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a></td>
                    <td>{{ post.writer.email }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <!-- 글이 없을 때 : 문구 출력 -->
        <p>작성된 게시물이 없습니다.</p>
    {% endif %}

{% endblock %}